### ISSUE TITLE
Missing VG.pt and object_count.pkl on the scene_graph branch

### ISSUE THREAD

**Issue by stoneMo** [suprosanna/relationformer#3]
Hi authors, congratulations on a great work for unifying the image-to-graph generation framework. i wonder where should VG.pt and object_count.pkl be downloaded for reproducing the results in terms of training and inference. Thanks.

**Comment by rajatkoner08** [comment]
Thank you for your interest, I have added a link in the readme file in the scene graph branch.

**Comment by stoneMo** [comment]
Thanks for your quick update. Downloaded it and closed this issue.
