### ISSUE TITLE
Problem about Compiling CUDA operators

### ISSUE THREAD

**Issue by Fillip1233** [suprosanna/relationformer#6]
Hello, the author. Thank you very much for publishing this excellent work. Some problems occurred when I ran the statement Compiling CUDA operators. Can you help me solve them？
<img width="809" alt="image" src="https://user-images.githubusercontent.com/89203680/201075553-4fbf20c1-49a5-4324-b59d-89b7a353b1c6.png">
<img width="555" alt="image" src="https://user-images.githubusercontent.com/89203680/201075662-d5a6159c-83ff-4d00-9522-42df95a9668d.png">

**Comment by rajatkoner08** [comment]
What is your PyTorch version ? and the Cuda version? This CUDA compilation exactly follows like deformable-detr, you take some help form their repository

**Comment by Fillip1233** [comment]
Thank you very much for taking the time to answer my question. I successfully solved the problem after I set it according to the configuration of deformable-detr. Thank you again!
